Synced on 20/01/24 06:14:23 AM CST

diff --git a/fehbg b/fehbg
--- a/fehbg
+++ b/fehbg
@@ -1,11 +1,17 @@
 #!/bin/sh
-file='/home/aarya/Notes/favorite_wallpapers.txt'
-if [ -f $file ];
-then
-	wallpaper="$(cat $file | shuf -n 1)"
+wallpaper="/home/aarya/wallpapers/arcolinux/koi-fishes-1920x1080.png"
+if [ ! -z "$wallpaper" ] && [ -f "$wallpaper" ]; then
 	echo $wallpaper
 	feh --no-fehbg --bg-scale "$wallpaper"
 else
-	echo "file not found: " $file
-	exit 1
+	file='/home/aarya/Notes/favorite_wallpapers.txt'
+	if [ -f $file ];
+	then
+		wallpaper="$(cat $file | shuf -n 1)"
+		echo $wallpaper
+		feh --no-fehbg --bg-scale "$wallpaper"
+	else
+		echo "file not found: " $file
+		exit 1
+	fi
 fi
