Synced on 27/12/23 06:05:09 PM IST

diff --git a/fehbg b/fehbg
--- a/fehbg
+++ b/fehbg
@@ -1,2 +1,11 @@
 #!/bin/sh
-feh --no-fehbg --bg-scale '/home/aarya/wallpapers/arcolinux/arco-login-plasma.jpg' 
+file='/home/aarya/Notes/favorite_wallpapers.txt'
+if [ -f $file ];
+then
+	wallpaper=$(cat $file | shuf -n 1)
+	echo $wallpaper
+	feh --no-fehbg --bg-scale $wallpaper
+else
+	echo "file not found: " $file
+	exit 1
+fi
